[project]
name = "scraper_service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ye-chuan", email = "76342787+ye-chuan@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
]

[project.scripts]
scraper_service = "scraper_service:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
